// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NashDom.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NashDom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<double>("ColdWater")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("HotWater")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("NashDom.Models.Accrual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccrualDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PersonalAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAccountId");

                    b.ToTable("Accruals");
                });

            modelBuilder.Entity("NashDom.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Car")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Entrance")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentNumber")
                        .IsUnique();

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("NashDom.Models.MeterReplacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ColdWaterMeterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ColdWaterMeterNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColdWaterNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ColdWaterVerificationYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HotWaterMeterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HotWaterMeterNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HotWaterNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HotWaterVerificationYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("MeterReplacements");
                });

            modelBuilder.Entity("NashDom.Models.OrganizationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrespondentAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterText")
                        .HasColumnType("text");

                    b.Property<string>("HeaderText")
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettlementAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrganizationSettings");
                });

            modelBuilder.Entity("NashDom.Models.PersonalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("ApartmentId");

                    b.ToTable("PersonalAccounts");
                });

            modelBuilder.Entity("NashDom.Models.RegistrationCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("ArrivedApartment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivedBuilding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ArrivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArrivedFromCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivedFromDistrict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivedFromRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivedFromStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivedHouse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BirthPlaceCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthPlaceDistrict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthPlaceRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthPlaceVillage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeregistrationNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentIssuedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentSeries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MilitaryNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResidenceApartment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResidenceBuilding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResidenceHouse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResidenceLocality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResidenceStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId")
                        .IsUnique();

                    b.ToTable("RegistrationCards");
                });

            modelBuilder.Entity("MeterReading", b =>
                {
                    b.HasOne("NashDom.Models.Apartment", "Apartment")
                        .WithMany("MeterReadings")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("NashDom.Models.Accrual", b =>
                {
                    b.HasOne("NashDom.Models.PersonalAccount", "PersonalAccount")
                        .WithMany()
                        .HasForeignKey("PersonalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAccount");
                });

            modelBuilder.Entity("NashDom.Models.MeterReplacement", b =>
                {
                    b.HasOne("NashDom.Models.Apartment", "Apartment")
                        .WithMany("MeterReplacements")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("NashDom.Models.PersonalAccount", b =>
                {
                    b.HasOne("NashDom.Models.Apartment", "Apartment")
                        .WithMany("PersonalAccounts")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("NashDom.Models.RegistrationCard", b =>
                {
                    b.HasOne("NashDom.Models.Apartment", "Apartment")
                        .WithOne("RegistrationCard")
                        .HasForeignKey("NashDom.Models.RegistrationCard", "ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("NashDom.Models.Apartment", b =>
                {
                    b.Navigation("MeterReadings");

                    b.Navigation("MeterReplacements");

                    b.Navigation("PersonalAccounts");

                    b.Navigation("RegistrationCard");
                });
#pragma warning restore 612, 618
        }
    }
}
